version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: Sample Application
    commands:
      - npm install
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
