version: Sample Application

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
